### ISSUE TITLE
Use Twig2 RuntimeLoader

### ISSUE THREAD

**Issue by romainneutron** [nelmio/NelmioSecurityBundle#131]
As proposed in https://github.com/nelmio/NelmioSecurityBundle/issues/129#issuecomment-275900662

**Comment by cordoval** [comment]
currently, does the twig extension gets loaded all the time?

**Comment by sstok** [comment]
@cordoval Yes it does. Looking at the current implementation, it's possible to change this.

The ShaComputer is injected so you can pre-compute the hash if the content is static text.
So you would have to remove this optimization (although this dependency is not to heavy).

The `ContentSecurityPolicyListener` can easily be loaded using a RuntimeLoader, make the Function require the Twig context so you can access the RuntimeLoaders and no need for a custom Node 👍

**Comment by stof** [comment]
Well, it would be much better to move the definition of `getCSPNonce` to a runtime class instead, and let Twig compile the call to the function to use this runtime, instead of using `$env->getRuntime` yourselves in the extension method (which is not the intended way to use this feature).

The ShaComputer is indeed not a heavy dependency, so it may not be worth avoiding its instantiation at the cost of removing an optimization.

**Comment by stof** [comment]
however, not that the listener is a kernel.request and kernel.response listener anyway. So avoiding to instantiate it for the Twig extension may not be worth it. The event dispatcher will instantiate it for all requests anyway (so the benefit would be for the CLI only)

**Comment by franmomu** [comment]
oops, I didn't see this issue when implementing https://github.com/nelmio/NelmioSecurityBundle/pull/283, closing since it was moved to a runtime class.
