### ISSUE TITLE
Compatibility issue with Twig 2.7.0

### ISSUE THREAD

**Issue by Toflar** [nelmio/NelmioSecurityBundle#197]
Twig 2.7.0 was released which now causes (at least) the following compat error:

```
Compile Error: Declaration of Nelmio\SecurityBundle\Twig\TokenParser\AbstractCSPParser::parse(Twig_Token $token) must be compatible with Twig\TokenParser\TokenParserInterface::parse(Twig\Token $token)
```

**Comment by kiler129** [comment]
Are you planning to offer a PR here?

**Comment by ls-philippe-gamache** [comment]
The problem, we need to upgrade to TWIG 2.7 as 2.6.2 have a security bug : [CVE-NONE-0001][]: Sandbox Information Disclosure

**Comment by ls-philippe-gamache** [comment]
Maybe there should be a version 3 with PHP 7.2 support for Encrypted Cookies, and Twig 2.7. And Symfony 4+ (maybe even 4.2 to remove legacy).

**Comment by kiler129** [comment]
The one option is to add the following in the current release:

```
    "conflict": {
        "twig/twig": ">=2.7.0"
    },
```

and produce new release which uses namespaced classes which conflicts with `twig/twig: "<2.0"`.

The case is evolving since it seems that break wasn't intentional and it's getting patched in https://github.com/twigphp/Twig/pull/2887. If this patch resolves the problem we simply need to add:

```
    "conflict": {
        "twig/twig": ">=2.7.0,<=2.7.1"
    },
```

This will solve the problem, since anyone trying to update will not install `2.7.0` which broke the NS and `2.7.1` which contains broken NS and security fix, but the installation of `2.7.2` with the fix will be allowed.

**Comment by Seldaek** [comment]
Make sure you update to latest twig releases which fixed this regression.

**Comment by ls-philippe-gamache** [comment]
Thanks Jordi!
