### ISSUE TITLE
[Symfony3] Wrong with log external Redirect

### ISSUE THREAD

**Issue by VuiLenDi** [nelmio/NelmioSecurityBundle#78]
I want to log all external redirect, so I set configure:

	// security.yml
	nelmio_security:
		external_redirects:
	        log: true
	        abort: true

**Problem:**

	ContextErrorException in ExternalRedirectListener.php line 39: Catchable Fatal Error: Argument 5 passed to Nelmio\SecurityBundle\EventListener\ExternalRedirectListener::__construct() must be an instance of Symfony\Component\HttpKernel\Log\LoggerInterface, instance of Symfony\Bridge\Monolog\Logger given, called in /vagrant/generic/var/cache/dev/appDevDebugProjectContainer.php on line 2131 and defined

**Reason:**

	The `Symfony\Component\HttpKernel\Log\LoggerInterface` has been removed in favor of `Psr\Log\LoggerInterface`

So I think we need update file: `ExternalRedirectListener.php`, remove `Symfony\Component\HttpKernel\Log\LoggerInterface` and update with `Psr\Log\LoggerInterface`

**Comment by sstok** [comment]
The LoggerInterface is deprecated since Symfony 2.2 but it's possible there are still packages out there that are using this interface (and this bundle still supports Symfony 2.3).

So instead of updating the typehint, it should be removed and we need check if eg. an instance of `Psr\Log\LoggerInterface` or `Symfony\Component\HttpKernel\Log\LoggerInterface` is provided.

There is only one one line where the logger is used: https://github.com/nelmio/NelmioSecurityBundle/blob/master/EventListener/ExternalRedirectListener.php#L81 and this needs to check which interface is used (at least until support for Symfony 2.x is dropped).

**Comment by gencer** [comment]
@VuiLenDi for now (totally temporarily) you may use my repository:

https://github.com/gencer/nelmio-symfony3

`$ compose require "gencer/nelmio-symfony3"`

**Comment by Seldaek** [comment]
Should be fixed now, I just migrated to PSR-3 logger because frankly 2.2 is very old, and this would only affect someone implementing their own logger against this outdated interface, while most people use monolog as it's been shipping with symfony2 since day one. I think it's safe enough and if not it should be easy for people to upgrade anyway.

**Comment by sstok** [comment]
Thanks @Seldaek
